DROP TABLE IF EXISTS candlestick;
CREATE TABLE candlestick(ID INT AUTO_INCREMENT PRIMARY KEY, SYMBOL VARCHAR(255), OPEN_TIME BIGINT, OPEN DOUBLE, HIGH DOUBLE, LOW DOUBLE, CLOSE DOUBLE, VOLUME DOUBLE, CLOSE_TIME BIGINT, QUOTE_ASSET_VOLUME DOUBLE, NUMBER_OF_TRADES INT, TAKER_BUY_BASE_VOLUME DOUBLE, TAKER_BUY_QUOTE_VOLUME DOUBLE);

CREATE INDEX idx_symbol
ON candlestick (symbol);